PREFIX : <http://example.org/def/ekg/aggregated_traces/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT
  ?event
  ?type
  ?sum_amount_in
  ?entity_amount_in
  ?sum_amount_out
  ?entity_amount_out
  (str(?sum_amount_in=?sum_amount_out) as ?equal)
  ?class
WHERE {
  ?event prov:atTime [] .

  { SELECT ?event ?type ?class (sum(xsd:float(strafter(?entity_amount_in, "|"))) as ?sum_amount_in) (group_concat(?entity_amount_in ; separator=", ") as ?entity_amount_in) {
    { SELECT DISTINCT ?event ?type ?class (concat(?entity, "|", str(?amount_in)) as ?entity_amount_in) {
      VALUES ?type {
        :DirectlyFollows_AggregatedEntity
        :DirectlyPrecedes_AggregatedEntity
      }
      [] a ?type ;
        :target ?event ;
        :quantity [
          :amount ?amount_in ;
          :class ?class ;
          :fromEntity/rdfs:label ?entity ;
        ] .
    }}
  } GROUP BY ?event ?type ?class }

  { SELECT ?event ?type ?class (sum(xsd:float(strafter(?entity_amount_out, "|"))) as ?sum_amount_out) (group_concat(?entity_amount_out ; separator=", ") as ?entity_amount_out) {
    { SELECT DISTINCT ?event ?type ?class (concat(?entity, "|", str(?amount_out)) as ?entity_amount_out) {
      VALUES ?type {
        :DirectlyFollows_AggregatedEntity
        :DirectlyPrecedes_AggregatedEntity
      }
      [] a ?type ;
        :source ?event ;
        :quantity [
          :amount ?amount_out ;
          :class ?class ;
          :fromEntity/rdfs:label ?entity ;
        ] .
    }}
  } GROUP BY ?event ?type ?class }
}
GROUP BY ?event ?type
ORDER BY ?type DESC(?equal)