PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
  ?nodeIn
  ?nodeOut
  (coalesce(?edge_amount, "") as ?edge_amount)
  (group_concat(distinct concat(str(?edge_amount), " - ", ?entity_label, " [", ?edge_class, "]"); separator="\n") as ?edge_amountEntityClass)
  (coalesce(?edge_fraction, "") as ?edge_fraction)
WHERE {
  ?DFRelation a :DirectlyFollows ;
    :source ?nodeIn ;
    :target ?nodeOut .
  OPTIONAL { ?DFRelation :fraction ?edge_fraction }
  OPTIONAL {
    ?DFRelation :quantity [
        :amount ?edge_amount ;
        :class ?edge_class ;
        :fromEntity ?entity ;
      ] .

    OPTIONAL { ?entity rdfs:label ?_entity_label }
    BIND ( coalesce(?_entity_label, replace(str(?entity), ".+/([a-zA-Z0-9_]+)$", "$1")) as ?entity_label )
  }
}
GROUP BY ?DFRelation