PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
  ?node
  ?node_operation
  (concat(?node_label, str(?time)) as ?node_label)
WHERE {
  [] :source|:target ?node .
  ?node rdfs:label ?node_label ;
    prov:entity/rdfs:label ?entity_label ;
    prov:atTime ?time .
}
GROUP BY ?node