PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
  ?node
  ?node_label
  (group_concat(distinct str(?node_type)) as ?node_types)
  (concat(group_concat(?entity_label), " @ ", str(?time)) as ?node_entitiesTime)
WHERE {
  [] :source|:target ?node .
  ?node a ?node_type ;
    prov:entity ?entity ;
    prov:atTime ?time .

  OPTIONAL { ?node rdfs:label ?_node_label }
  BIND ( coalesce(?_node_label, replace(str(?node), ".+/([a-zA-Z0-9_]+)$", "$1")) as ?node_label )

  OPTIONAL { ?entity rdfs:label ?_entity_label }
  BIND ( coalesce(?_entity_label, replace(str(?entity), ".+/([a-zA-Z0-9_]+)$", "$1")) as ?entity_label )
}
GROUP BY ?node