PREFIX : <http://example.org/def/ekg/aggregated_traces/>

#TODO: distinguish by type of material (contained in the aggregated entity)
SELECT DISTINCT
  ?event
  ?type
  ?product
  ?sum_amount_in
  (replace(?entity_amount_in, str(<>), "") as ?_entity_amount_in)
  ?sum_amount_out
  (replace(?entity_amount_out, str(<>), "") as ?_entity_amount_out)
  (?sum_amount_in=?sum_amount_out as ?equal)
WHERE {
  ?event :timestamp [] .

  { SELECT ?event ?product ?type (sum(xsd:float(strafter(?entity_amount_in, "|"))) as ?sum_amount_in) (group_concat(?entity_amount_in ; separator=", ") as ?entity_amount_in) {
    # Pipe separator (https://www.rfc-editor.org/rfc/rfc3986)
    { SELECT ?event ?product ?type (concat(str(?entity), "|", str(?amount_in)) as ?entity_amount_in) {
      VALUES ?type {
        :DirectlyFollows_AggregatedEntity
        :DirectlyPrecedes_AggregatedEntity
      }
      ?relation a ?type ;
        :target ?event ;
        :amount ?amount_in ;
        :class ?entity .

      ?entity a :AggregatedEntity .

      OPTIONAL {
        ?relation :class ?product .
        ?product a :Product .
      }
    }}
  } GROUP BY ?event ?product ?type }

  { SELECT ?event ?product ?type (sum(xsd:float(strafter(?entity_amount_out, "|"))) as ?sum_amount_out) (group_concat(?entity_amount_out ; separator=", ") as ?entity_amount_out) {
    { SELECT ?event ?product ?type (concat(str(?entity), "|", str(?amount_out)) as ?entity_amount_out) {
      VALUES ?type {
        :DirectlyFollows_AggregatedEntity
        :DirectlyPrecedes_AggregatedEntity
      }
      _:relation a ?type ;
        :source ?event ;
        :amount ?amount_out ;
        :class ?entity .

      ?entity a :AggregatedEntity .

      OPTIONAL {
        _:relation :class ?product .
        ?product a :Product .
      }
    }}
  } GROUP BY ?event ?product ?type }
}
GROUP BY ?event ?product ?type
ORDER BY ?type DESC(?equal)
