PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
    ?g
    ?entity_source
    ?node_source
    # Work around for filter that does not work
    (?node_source_time>=?window_start && ?node_source_time<=?window_end as ?flag_in_window)
    ?entity_target
    ?node_target
    (coalesce(?intersection_size/?source_size, "N/A") as ?validation_fraction)
WHERE {
    {
        ?node_source :bizStep "departing" ;
            :timestamp ?node_source_time ;
            :location ?entity_source .
    } UNION {
        ?node_source :bizStep "creating_class_instance" ;
            :timestamp ?node_source_time ;
            :entity ?entity_source .
    }

    # Use graph context to only traverse edges in one direction (DirectlyFollows or DirectlyPrecedes) 
    GRAPH ?g { ?node_source (^:source/:target)+ ?node_target }

    ?node_target :parentEntity ?entity_target .

    # Only include packing units
    ?entity_target a :PackingUnit ;
        rdfs:label ?entity_target_label .

    # Exclude nodes without common devices (empty intersection set)
    # { SELECT DISTINCT ?node_target ?node_source (count(distinct ?unit) as ?intersection_size) {
    #     ?node_source :device|:material ?unit .
    #     ?node_target :device/:material? ?unit .
    # } GROUP BY ?node_target ?node_source }

    # { SELECT DISTINCT ?node_source (count(distinct ?unit) as ?source_size) {
    #     ?node_source :device|:material ?unit .
    # } GROUP BY ?node_source}
}
