PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
  ?g
  ?entity_source
  ?node_source
  ?entity_target
  ?node_target
  ?product_model
  ?devices_quality
WHERE {
  ?node_source :parentEntity ?entity_source .

  # Use graph context to only traverse edges in one direction (DirectlyFollows or DirectlyPrecedes) 
  GRAPH ?g { ?node_source (^:source/:target)+ ?node_target }

  ?node_target :bizStep "departing" ;
    :location ?entity_target .

  ?node_target :quantity/:class ?product_model .
  ?product_model a :Product .

  OPTIONAL {
    {
      SELECT DISTINCT ?node_source (group_concat(distinct ?device_quality; separator=",") as ?devices_quality)
      WHERE {
        ?node_source :bizStep "packing" ;
          :device ?device .

        ?device :quality ?quality .
        bind (concat(str(?device), "|", str(?quality)) as ?device_quality)
      }
      GROUP BY ?node_source
    }
  }
}
