PREFIX : <http://example.org/def/ekg/aggregated_traces/>

SELECT DISTINCT
  ?Relation
  ?nodeSource
  ?nodeTarget
  (str(?type) as ?edge_type)
  (coalesce(?_edge_amount, "") as ?edge_amount)
  (group_concat(distinct concat(
    str(?_edge_amount), " - ",
    ?entity_label
  ); separator="\n") as ?edge_amountEntity)
  (group_concat(distinct concat(
    coalesce(?entity_label, ""), " [",
    coalesce(str(?_edge_amount), ""), "] {",
    coalesce(str(round(?_edge_fraction*100)/100), ""), "}" # round to two decimals
  ); separator="\n") as ?edge_amountEntityFraction)
  (coalesce(?_edge_fraction, "") as ?edge_fraction)
WHERE {
  VALUES ?type {
    :DirectlyFollows
    :DirectlyPrecedes
  }
  ?Relation a ?type ;
    :source ?nodeSource ;
    :target ?nodeTarget .
  OPTIONAL { ?Relation :fraction ?_edge_fraction }
  OPTIONAL {
    ?Relation :amount ?_edge_amount ;
      :class ?entity .
    ?entity a :AggregatedEntity .

    OPTIONAL { ?entity rdfs:label ?_entity_label }
    BIND ( coalesce(?_entity_label, replace(str(?entity), ".+/([a-zA-Z0-9_]+)$", "$1")) as ?entity_label )
  }
}
GROUP BY ?Relation
