@startuml
set namespaceSeparator none

package "Core Meta-Model\n(Esser and Fahland, 2021; Fahland, 2022)" <<Rectangle>> {
    object Event #LightBlue {
        activity : string
        timestamp : datetime
    }
    object Entity #LightGreen {
        id : string
        type : string
    }
    object Activity #Yellow {
        name : string
    }
    ' object Log #SkyBlue {
    '     id : string
    ' }

    Event --> Entity : entity
    Event --> Activity : observed
    Entity --> Entity : relation
    ' Log --> Event : event

    Activity --> Activity : directlyFollowsActivity

    object "EventRelation_AggregatedEntity" as DF_DP #LightYellow {
        entity: Entity [1..*]
    }
    (Event, Event) . DF_DP

    object "DirectlyFollows" as DF
    object "DirectlyPrecedes" as DP
    DF -d-|> DF_DP
    DP -d-|> DF_DP

    DF_DP -[hidden]r- Event
}

package "Extension\n(based on EPCIS2.0; 'EPCIS and CBV Implementation Guideline')" <<Rectangle>> {
    object EPCISEvent
    EPCISEvent --|> Event
    object Aggregation {
        action: string ("ADD" "DELETE")
        parentEntity: AggregatedEntity
        childQuantity: Quantity [1..*]
    }
    object Object {
        entity: AggregatedEntity
        quantity: Quantity [0..*]
    }
    object Transformation {
        inputQuantity: Quantity [1..*]
        outputQuantity: Quantity [1..*]
    }
    Object -u-|> EPCISEvent
    Aggregation -u-|> EPCISEvent
    Transformation -u-|> EPCISEvent

    object Product

    object AggregatedEntity
    AggregatedEntity -l-|> Entity

    object Quantity {
        amount : double
    }
    Object --> Quantity : quantity
    Aggregation --> Quantity : childQuantity
    Aggregation --> AggregatedEntity : parentEntity
    Transformation --> Quantity : inputQuantity
    Transformation --> Quantity : outputQuantity
    Quantity --> AggregatedEntity : class
    Quantity --> Product : class

    object "EventRelation_AggregatedEntity" as DF_DP_AggregatedEntity #LightYellow {
        amount: double
        fraction: decimal
    }
    (EPCISEvent, EPCISEvent) . DF_DP_AggregatedEntity

    ' Quantity -[hidden]- AggregatedEntity
    ' AggregatedEntity -[hidden]- Product
}
@enduml