@startuml
' https://crashedmind.github.io/PlantUMLHitchhikersGuide/layout/layout.html

set namespaceSeparator none
' left to right direction

' package "EKG pattern" <<Rectangle>> {

    object "Quantity" as Quantity1 {
        amount: q<sub>1</sub>
        class: c<sub>1</sub>
    }
    object "Quantity" as Quantity2 {
        amount: q<sub>2</sub>
        class: c<sub>1</sub>
    }
    object "Quantity" as Quantity3 {
        amount: q<sub>3</sub>
        class: c<sub>1</sub>
    }

    object "AggregatedEntity" as AggregatedEntity1 #LightGreen
    object "AggregatedEntity" as AggregatedEntity2 #LightGreen
    object "AggregatedEntity" as AggregatedEntity3 #LightGreen

    object "Event" as Event1 #LightBlue {
        timestamp : t<sub>1</sub>
    }
    object "Aggregation" as Event2 #LightBlue {
        timestamp : t<sub>2</sub>
        action : DELETE
    }
    object "Event" as Event3 #LightBlue {
        timestamp : t<sub>3</sub>
    }
    object "Event" as Event4 #LightBlue {
        timestamp : t<sub>4</sub>
    }

    ' Event1 -[norank]-> AggregatedEntity1 #LightGrey : entity
    Event2 -[norank]-> AggregatedEntity1 #LightGrey : parentEntity
    Event3 -[norank]-> AggregatedEntity2 #LightGrey : entity
    Event4 -[norank]-> AggregatedEntity3 #LightGrey : entity

    Event1 --> Quantity1 #Grey : quantity
    Event2 --> Quantity2 #Grey : childQuantity
    Event2 --> Quantity3 #Grey : childQuantity
    Quantity1 --> AggregatedEntity1 #Grey : class
    Quantity2 --> AggregatedEntity2 #Grey : class
    Quantity3 --> AggregatedEntity3 #Grey : class
' }

' package "Directly follows (derived)" <<Rectangle>> {
    Event1 --> Event2 : directlyFollows_AggregatedEntity
    object "DirectlyFollows_AggregatedEntity" as DF1_2 #LightYellow {
        amount: q<sub>1</sub>
        ' fraction:
    }
    (Event1, Event2) . DF1_2

    Event2 --> Event3 : directlyFollows_AggregatedEntity
    object "DirectlyFollows_AggregatedEntity" as DF2_3 #LightYellow {
        amount: q<sub>2</sub>
        fraction: q<sub>2</sub>/q<sub>1</sub>
    }
    (Event2, Event3) . DF2_3

    Event2 --> Event4 : directlyFollows_AggregatedEntity
    object "DirectlyFollows_AggregatedEntity" as DF2_4 #LightYellow {
        amount: q<sub>3</sub>
        fraction: q<sub>3</sub>/q<sub>1</sub>
    }
    (Event2, Event4) . DF2_4
' }

DF2_3 -l[hidden]- Quantity2
' Event2 -l[hidden]- Merge
' AggregatedEntity1State1 -r[hidden]- AggregatedEntity2State1
@enduml